# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-8lq90oeQhUqM22D3u_p1OaXqmicYIc
"""

print('Hello') #this is a python comment and I am learning python
print("My name is Syed Mujtaba Ali, I am 22 years old starting my Python journey")