# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVvt8hGgWVEeD8hyXR6SSuz9GTmZ4uyg
"""

#Day 2 of python programming and I have self learnt the commands to create a small calculator
print("Welcome to Syed Mujtaba Ali's personal calculator")
print("To add+ press 1")
print("To sub- press 2")
print("To mul* press 3")
print("To div/ press 4")
print("To mod% press 5")
print("To square^2 press 6")
print("To cube^3 press 7")
a=int(input("Enter the operation you want to perform: "))
if a==1:
  b=int(input("Enter the first number: "))
  c=int(input("Enter the second number: "))
  print(b+c)
elif a==2:
  b=int(input("Enter the first number: "))
  c=int(input("Enter the second number: "))
  print(b-c)
elif a==3:
  b=int(input("Enter the first number: "))
  c=int(input("Enter the second number: "))
  print(b*c)
elif a==4:
  b=int(input("Enter the first number: "))
  c=int(input("Enter the second number: "))
  print(b/c)
elif a==5:
  b=int(input("Enter the first number: "))
  c=int(input("Enter the second number: "))
  print(b%c)
elif a==6:
  b=int(input("Enter the number: "))
  print(b*b)
elif a==7:
 b=int(input("Enter the number: "))
 print(b * b * b)
else:
  print("Invalid input")