# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxUnd-IzZrkX5JC26ZQtjHIwnjI3BL9X
"""

print("Welcome user, kindly enter your name!")
name=str(input("name:"))
print("Name received from user, kindly enter your age!")
age=int(input("age:"))
print("Thank you for giving information")